'\" t
.\"     Title: cgps
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD Version 3.25
.\"  Language: English
.\"
.TH "CGPS" "1" "2023-01-10" "GPSD Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cgps \- curses terminal client for gpsd
.SH "SYNOPSIS"
.sp
\fBcgps\fP [OPTIONS] [server[:port[:device]]]
.sp
\fBcgps\fP \-h
.sp
\fBcgps\fP \-V
.SH "DESCRIPTION"
.sp
\fBcgps\fP is an ncurses based \fBgpsd\fP client. It is able to run on a serial
terminal or terminal emulator. It resembles \fBxgps\fP(1), but without the
pictorial satellite display and does not require X or other windowing
system.
.sp
\fBcgps\fP does not require root privileges. It will also run fine as root.
Running under sudo will cause loss of functionality.
.sp
None of the error estimates provided by \fBgpsd\fP, and displayed by \fBcgps\fP,
should be taken as anything other than "goodness" levels.  GNSS receiver
manufactures often do not document the basis for their estimates.  Those
that do document their estimates are inconsistent about what they mean.
.SH "OPTIONS"
.sp
\fB\-?\fP, \fB\-h\fP, \fB\-\-help\fP
.RS 4
Print a summary of options and then exit.
.RE
.sp
\fB\-D LVL\fP, \fB\-\-debug LVL\fP
.RS 4
Sets the debug level; it is primarily for use by GPSD developers. It
enables various progress messages to standard error.
.RE
.sp
\fB\-i\fP, \fB\-\-imu\fP
.RS 4
Show IMU instead of fix and satellite data.
.RE
.sp
\fB\-l FMT\fP, \fB\-\-llfmt FMT\fP
.RS 4
Sets the format of latitude and longitude reports. The value \*(Aqd\*(Aq
produces decimal degrees and is the default. The value \*(Aqm\*(Aq produces
degrees and decimal minutes. The value \*(Aqs\*(Aq produces degrees, minutes,
and decimal seconds.
.RE
.sp
\fB\-m\fP, \fB\-\-magtrack\fP
.RS 4
Display tracks as magnetic, not true.
.RE
.sp
\fB\-m\fP, \fB\-\-magtrack\fP
.RS 4
Display your magnetic track (as opposed to your true track). This is a
calculated value, not a measured value. Magnetic variation is always
potentially subject to large errors, but is usually better than two
degrees.
.RE
.sp
\fB\-s\fP, \fB\-\-silent\fP
.RS 4
Prevents \fBcgps\fP from displaying the raw data coming from the daemon. This
display can also be toggled with the s command.
.RE
.sp
\fB\-u UNITS\fP, \fB\-\-units UNITS\fP
.RS 4
Set the system units for display; follow the keyword with \*(Aqi\*(Aq for
\*(Aqimperial\*(Aq for American units (International Feet in altitude and
error estimates, miles per hour in speeds), \*(Aqn\*(Aq for \*(Aqnautical\*(Aq (feet
in altitude and error estimates, knots in speed) or \*(Aqm\*(Aq for \*(Aqmetric\*(Aq
(meters in altitude and error estimates, kilometers per hour in
speeds).
.sp
Note: The USA Survey Foot is not supported.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print the package version and exit.
.RE
.SH "ARGUMENTS"
.sp
By default, clients collect data from the local \fBgpsd\fP daemon running
on localhost, using the default GPSD port 2947. The optional argument
to any client may override this behavior: \fB[server[:port[:device]]]\fP
.sp
For further explanation, and examples, see the \fBARGUMENTS\fP section in
the \fBgps\fP(1) man page
.SH "COMMANDS"
.sp
\fBcgps\fP terminates when you send it a SIGHUP or SIGINT; given default
terminal settings this will happen when you type Ctrl\-C at it.
.sp
\fBcgps\fP will accept a few single letter commands while running:
.sp
\fBc\fP
.RS 4
Clear the bottom window.
.RE
.sp
\fBd\fP
.RS 4
Show lat/lon dd.dddddddd, dd mm.mmmmmm and dd mm ss.ssss
.RE
.sp
\fBh\fP
.RS 4
Popup a help window.
.RE
.sp
\fBi\fP
.RS 4
Use imperial units.
.RE
.sp
\fBm\fP
.RS 4
Use metric units.
.RE
.sp
\fBn\fP
.RS 4
Use nautical units.
.RE
.sp
\fBq\fP
.RS 4
Clear screen and exit
.RE
.sp
\fBs\fP
.RS 4
Toggle showing raw JSON data in the bottom window.
.RE
.sp
\fBt\fP
.RS 4
Toggle true/magnetic track.
.RE
.SH "ENVIRONMENT"
.sp
The environment variable \fBGPSD_UNITS\fP is checked if no unit system is
specified on the command line. It may be set to \*(Aqi\*(Aq. \*(Aqimperial\*(Aq, \*(Aqm\*(Aq,
\*(Aqmetric\*(Aq, or \*(Aqn\*(Aq, \*(Aqnautical\*(Aq.
.sp
LC_MEASUREMENT and then LANG are checked if no unit system has
been specified on the command line, or in GPSD_UNITS. If the value
is \*(AqC\*(Aq, \*(AqPOSIX\*(Aq, or begins with \*(Aqen_US\*(Aq the unit system is set to
imperial. The default if no system has been selected defaults to metric.
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.sp
\fB1\fP
.RS 4
on failure
.RE
.SH "SEE ALSO"
.sp
\fBgegps\fP(1), \fBgpsctl\fP(1), \fBgps\fP(1), gpsprof*(1), \fBgpsfake\fP(1),
\fBgpscat\fP(1), \fBgpspipe\fP(1), \fBgpsmon\fP(1), xgps*(1). \fBxgpsspeed\fP(1)
.sp
\fBlibgps\fP(3), \fBlibgpsmm\fP(3)
.sp
\fBgpsd\fP(8)
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2013 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause