'\" t
.\"     Title: gpsdebuginfo
.\"    Author: Gary E. Miller
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD Version 3.25
.\"  Language: English
.\"
.TH "GPSDEBUGINFO" "1" "2023-01-10" "GPSD Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
gpsdebuginfo \- Generate a gpsd debug dump of your host.
.SH "SYNOPSIS"
.sp
\fBgpsdebuginfo\fP
.SH "DESCRIPTION"
.sp
\fBgpsdebuginfo\fP is a shell script to run a series of short tests to
see the state of \fBgpsd\fP on you machine.  Run it, and send the complete
output, without change, when you request support help.
.sp
The script should not collect any Personally Identifiable Information
(PII).  You may wish to study the output before sending it to verify that.
.sp
\fBgpsdebuginfo\fP should be run as root.  It may be run as a normal user,
but with loss of functionality.  Running under \fBsudo\fP may cause
misleading results.
.SH "OPTIONS"
.sp
None.
.SH "ENVIRONMENT"
.sp
This script depends on the following environment variables:
.sp
PATH
.RS 4
To find \fBgpsd\fP, \fBgpspipe\fP, and other installed \fBgpsd\fP parts.
.RE
.sp
PYTHONPATH
.RS 4
To find the \fBgps\fP Python module.
.RE
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.SH "SEE ALSO"
.sp
\fBgpsd\fP(8), \fBcgps\fP(1), \fBgps\fP(1), \fBgpspipe\fP(1)
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2021 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause
.SH "AUTHOR"
.sp
Gary E. Miller