'\" t
.\"     Title: gpsinit
.\"    Author: Reinhard Arlt
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD, Version 3.25
.\"  Language: English
.\"
.TH "GPSINIT" "8" "2023-01-10" "GPSD, Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
gpsinit \- initialize CAN kernel modules for GPSD
.SH "SYNOPSIS"
.sp
\fBgpsinit\fP [\-n control] [\-s speed] module_name [interface_name]
.sp
\fBgpsinit\fP \-h
.sp
\fBgpsinit\fP \-V
.SH "DESCRIPTION"
.sp
\fBgpsinit\fP initializes whatever kernel\-level modules are needed to enable
special non\-serial hardware to communicate with a gpsd instance. Note:
it will need root permissions to load modules and perform other special
operations, such as changing kernel\-interface baudrates.
.sp
At present, all modes of this tool are concerned with setting up
kernel\-level interfaces to hardware on a CAN (Control Area Network)
speaking NMEA2000.
.sp
The program accepts the following options:
.sp
\fB\-h\fP
.RS 4
Display a brief help text.
.RE
.sp
\fB\-n\fP
.RS 4
Set the CAN network number. The default is 0.
.RE
.sp
\fB\-s\fP
.RS 4
Set the baudrate to be used to communicate over the serial line to the
CAN hardware. The default is 38400 baud.
.RE
.sp
\fB\-V\fP
.RS 4
Display the version of gpsinit.
.RE
.sp
The parameter \fBmodule_name\fP is mandatory. The socket CAN driver module
\fBmodule_name.ko\fP will be loaded. \fBgpsinit\fP recognize the following
module names:
.sp
\fBplx_pci\fP, \fBesd_usb2\fP, \fBvcan\fP, \fBslcan\fP
.RS 4
The parameter \fBinterface_name\fP and \fB\-s\fP \fBspeed\fP can used here.
.RE
.sp
\fBbeaglebone\fP
.RS 4
The dcan module needed for the beaglebone is part of the Linux kernel,
so no module is loaded in this case.
.RE
.sp
The parameter \fBinterface_name\fP is needed for slcan hardware only. It
gives the name of the serial device to which the SL CAN hardware is
connected. The default is /dev/ttyUSB0.
.SH "EXAMPLES"
.sp
All the following examples probably need to be run as root.
.sp
\fBgpsinit plx_pci\fP
.RS 4
Attempt to load the module plx_pci and initialize net 0 for the
connection to a NMEA2000 network. It will set the baudrate to
250kBits.
.RE
.sp
\fBgpsinit \-n 1 plx_pci\fP
.RS 4
As above, but use net 1.
.RE
.sp
\fBgpsinit \-s 38400 slcan /dev/ttyUSB0\fP
.RS 4
Attempt to load the module slcan and talk to the hardware at 38400
baud connected to port /dev/ttyUSB0.
.RE
.sp
\fBgpsinit \-h\fP
.RS 4
Display a brief help message.
.RE
.sp
\fBgpsinit \-v\fP
.RS 4
Display the version of gpsinit.
.RE
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.sp
\fB1\fP
.RS 4
on failure
.RE
.SH "SEE ALSO"
.sp
\fBgpsd\fP(8), \fBgps\fP(1)
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2013 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause
.SH "AUTHOR"
.sp
Reinhard Arlt