'\" t
.\"     Title: gpssubframe
.\"    Author: Gary E. Miller
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD Version 3.25
.\"  Language: English
.\"
.TH "GPSSUBFRAME" "1" "2023-01-10" "GPSD Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
gpssubframe \- tool to dump subframe sentences from gpsd
.SH "SYNOPSIS"
.sp
\fBgpssubframe\fP [OPTIONS] [server[:port[:device]]]
.sp
\fBgpssubframe\fP \-h
.sp
\fBgpssubframe\fP \-V
.SH "DESCRIPTION"
.sp
\fBgpssubframe\fP is a tool to connect to \fBgpsd\fP and dump decoded subframe data
to stdout. This is only useful if your GNSS receiver can output GPS
subframe messages, and is configured to do so. A working knowledge of
IS\-GPS\-200 is also required. Keep your copy close at hand.
.sp
\fBgpssubframe\fP does not require root privileges, but will run fine as
root.  It can be run concurrently with other tools connecting to the
local \fBgpsd\fP without causing problems.
.sp
The program will accumulate subframe messages and output them by GPS
satellite number on exit. By default the program never exits unless the
user selects the number of seconds to run or number of messages to
capture.
.sp
By default \fBgpssubframe\fP connects to a \fBgpsd\fP running on the local host.
Optionally a host, TCP/IP port number and remote device can be given.
.SH "OPTIONS"
.sp
\fB\-?\fP, \fB\-h\fP, \fB\-\-help\fP
.RS 4
\-Print a usage message and exit.
.RE
.sp
\fB\-c COUNT\fP, \fB\-\-count COUNT\fP
.RS 4
Exit after COUNT subframe messages.
.RE
.sp
\fB\-D DEBUG\fP, \fB\-\-debug DEBUG\fP
.RS 4
Set level of debug. Must be integer. Default 0.
.RE
.sp
\fB\-\-desc\fP
.RS 4
Print long descriptions.
.RE
.sp
\fB\-\-device DEVICE\fP
.RS 4
Connect to device DEVICE on \fBgpsd\fP host.
.RE
.sp
\fB\-D LVL\fP, \fB\-\-debug LVL\fP
.RS 4
Set debug level to LVL.
.RE
.sp
\fB\-\-file FILE\fP
.RS 4
Read gpsd JSON from FILE instead of from gpsd..
.RE
.sp
\fB\-\-host HOST\fP
.RS 4
Connect to gpsd on host HOST.
.RE
.sp
\fB\-\-load LOADFILE\fP
.RS 4
Load saved JSON Subframe, TPV, and RAW data trom LOADFILE.
.RE
.sp
\fB\-n COUNT\fP, \fB\-\-count COUNT\fP
.RS 4
Count of messages to parse. 0 to disable.
.RE
.sp
\fB\-\-port PORT\fP
.RS 4
Connect to \fBgpsd\fP on port PORT.
.RE
.sp
\fB\-\-progress\fP
.RS 4
Print progress reports as messages are received.
.RE
.sp
\fB\-\-satpos\fP
.RS 4
Compute GPS satellite positions before exit.  If \fB\-\-time\fP is given, the
positions will be calculated at the time.  Otherwise if a RAW message
was received, the measurement time in that message will be used.  The
last resort is to use the time from the last TPV message is used.
.RE
.sp
\fB\-\-save SAVEFILE\fP
.RS 4
Save decoded Subframe data in SAVEFILE as JSON.  If present, the last
TPV and RAW JSON records will also be saved.
.RE
.sp
\fB\-\-test\fP
.RS 4
Run \fB\-\-satpos\fP selftest code.
.RE
.sp
\fB\-\-time SEC\fP
.RS 4
Compute satellite position at time SEC in POSIX seconds.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
Print the program version, then exit.
.RE
.sp
\fB\-x SEC\fP, \fB\-\-seconds SEC\fP
.RS 4
Seconds of messages to parse. 0 to disable.
.RE
.SH "ARGUMENTS"
.sp
By default, clients collect data from the local \fBgpsd\fP daemon running
on localhost, using the default GPSD port 2947. The optional argument
to any client may override this behavior: \fB[server[:port[:device]]]\fP
.sp
For further explanation, and examples, see the \fBARGUMENTS\fP section in
the \fBgps\fP(1) man page
.SH "EXAMPLES"
.sp
First configure a u\-blox 9\-series to output subframe messages. Then have
\fBgpssubframe\fP gather one complete set of subframes, then print the data
organized by GPS satellite number.  Be sure to replace \fB\-P 22\fP with the
correct protocol version for your receiver. Then calculate and print the
known satellite positions as well as the azimuth, elevation, and range
from the current position:
.sp
.if n .RS 4
.nf
.fam C
ubxtool \-P 22 \-e SFRBX
gpssubframe \-x 750 \-\-satpos
.fam
.fi
.if n .RE
.sp
If staring at a blank screen for 12.5 minutes is too stressful, then
enable progress messages:
.sp
.if n .RS 4
.nf
.fam C
gpssubframe \-x 750 \-\-satpos \-\-progress
.fam
.fi
.if n .RE
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.sp
\fB1\fP
.RS 4
on failure
.RE
.SH "SEE ALSO"
.sp
\fBgpsd\fP(8), \fBgps\fP(1), \fBgpsprof\fP(1), \fBgpsfake\fP(1).
.sp
IS\-GPS\-200 "NAVSTAR GPS Space Segment/Navigation User Segment
Interfaces"
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2020 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause
.SH "AUTHOR"
.sp
Gary E. Miller