'\" t
.\"     Title: xgpsspeed
.\"    Author: Chen Wei, Robin Wittler
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD, Version 3.25
.\"  Language: English
.\"
.TH "XGPSSPEED" "1" "2023-01-10" "GPSD, Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
xgpsspeed \- X speedometer for gpsd
.SH "SYNOPSIS"
.sp
\fBxgpsspeed\fP [OPTIONS] [service[:port[:device]]]
.sp
\fBxgpsspeed\fP \-h
.sp
\fBxgpsspeed\fP \-V
.SH "DESCRIPTION"
.sp
\fBxgpsspeed\fP is a speedometer that uses position information from gpsd.
.sp
The default display mode is a speed and track presentation modeled after
a marine navigation display; for backward compatibility the \fB\-\-nautical\fP
option forces this mode. The \fB\-\-landspeed\fP option produces a simple
speedometer.
.sp
The \fB\-\-speedunits\fP option can be used to set the speed units for
display; follow the keyword with "knots" for nautical miles per hour,
"kmh" for kilometers per hour, or "mph" for miles per hour. The default
is miles per hour.
.sp
In the nautical mode only, \fB\-\-maxspeed\fP sets the maximum on the
speedometer.
.sp
\fBxgpsspeed\fP will run fine as a normal user, and fine as root.  Running
\fBxgpsspeed\fP under \fBsudo\fP will cause some loss of functionality.
.SH "OPTIONS"
.sp
\fB\-?\fP, \fB\-h\fP, \fB\-\-help\fP
.RS 4
Causes the client to emit a summary of its options and then exit.
.RE
.sp
\fB\-device DEVICE\fP
.RS 4
The device on the host to connect to. The default is empty (any).
.RE
.sp
\fB\-D LVL\fP, \fB\-\-debug LVL\fP
.RS 4
Sets the debug level, it is primarily for use by GPSD developers. It
enables various progress messages to standard error.
.RE
.sp
\fB\-\-host HOST\fP
.RS 4
The host (server) to connect to. The default is localhost.
.RE
.sp
\fB\-p PORT\fP, \fB\-\-port PORT\fP
.RS 4
The port to connect to. The default is 2947.
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.RS 4
This option causes each client to dump the package version and exit.
.RE
.SH "ARGUMENTS"
.sp
By default, clients collect data from the local \fBgpsd\fP daemon running
on localhost, using the default GPSD port 2947. The optional argument
to any client may override this behavior: \fB[server[:port[:device]]]\fP
.sp
For further explanation, and examples, see the \fBARGUMENTS\fP section in
the \fBgps\fP(1) man page
.SH "ENVIRONMENT"
.sp
The environment variable \fBGPSD_UNITS\fP is checked if no unit system is
specified on the command line.  It may be set to \*(Aqi\*(Aq. \*(Aqimperial\*(Aq, \*(Aqm\*(Aq,
\*(Aqmetric\*(Aq, or \*(Aqn\*(Aq, \*(Aqnautical\*(Aq.
.sp
\fBLC_MEASUREMENT\fP and then \fBLANG\fP are checked if no unit system has been
specified on the command line, or in \fBGPSD_UNITS\fP. If the value is \*(AqC\*(Aq,
\*(AqPOSIX\*(Aq, or begins with \*(Aqen_US\*(Aq the unit system is set to imperial. The
default if no system has been selected defaults to metric.
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.sp
\fB1\fP
.RS 4
on failure
.RE
.SH "SEE ALSO"
.sp
\fBgpsd\fP(8), \fBgps\fP(1), \fBxgps\fP(1)
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2013 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause
.SH "AUTHORS"
.sp
Chen Wei
.sp
Robin Wittler