'\" t
.\"     Title: zerk
.\"    Author: Gary E. Miller
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-01-10
.\"    Manual: GPSD Documentation
.\"    Source: GPSD, Version 3.25
.\"  Language: English
.\"
.TH "ZERK" "1" "2023-01-10" "GPSD, Version 3.25" "GPSD Documentation"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
zerk \- All purpose GREIS fitting
.SH "OPTIONS"
.sp
\fBzerk\fP [OPTIONS] [server[:port[:device]]]
.sp
\fBzerk\fP \-h
.sp
\fBzerk\fP \-V
.SH "DESCRIPTION"
.sp
\fBzerk\fP is an all purpose GREIS (GNSS Receiver External Interface
Specification) fitting. If you do not have a Javad GPS that speaks
the GREIS protocol then you can stop reading now.
.sp
This tool operates with your Javad GPS at a very low level. To
understand \fBzerk\fP you must first be familiar with your Javad GPS and the
documentation for the GREIS protocol.
.URL "https://www.javad.com/downloads/javadgnss/manuals/GREIS/GREIS_Reference_Guide.pdf" "GREIS Guide" "."
.sp
\fBzerk\fP can decode common GREIS messages, poll the GPS status, enable and
disable GPS features, and send user\-generated commands to the GPS. It
can read GREIS messages from a file. It can read and write directly
through a serial device, or through a running \fBgpsd\fP instance.
.sp
\fBzerk\fP does not require root privileges, except maybe to access the
serial port in direct mode.  It will run fine as root.  Running under
sudo will cause loss of functionality.
.SH "OPTIONS"
.sp
The program accepts the following options:
.sp
\fB\-?\fP, \fB\-h\fP
.RS 4
Makes \fBzerk\fP print a usage message and exit.
.RE
.sp
\fB\-c COMMAND\fP
.RS 4
Send a text string to the GPS. Accepts one parameter, COMMAND, the
command string to send to the GPS. The string is sent verbatim, except
a newline is appended.
.RE
.sp
\fB\-d OPTION\fP
.RS 4
Disable an option in the GPS. Accepts one parameter, OPTION, the
option to disable. \fBzerk\fP will exit after the GPS acknowledges the
command, unless the \fB\-W\fP is given.
.sp
4HZ
.RS 4
Disable basic GREIS messages at 4Hz. The messages
are: [RT], [UO], [GT], [PV], [SG], [DP], [SI], [EL], [AZ], [EC], [SS], and [ET]
.RE
.sp
COMPASS
.RS 4
Disable use of the COMPASS (BeiDou) constellation.
.RE
.sp
CONS
.RS 4
Disable use of all constellations.
.RE
.sp
DEFMSG
.RS 4
Disable the default message set (/dev/msg) at 1Hz.
.RE
.sp
GALILEO
.RS 4
Disable use of the GALILEO constellation.
.RE
.sp
GLONASS
.RS 4
Disable use of the GLONASS constellation.
.RE
.sp
GPS
.RS 4
Disable use of the GPS constellation.
.RE
.sp
IPR
.RS 4
Disable all Integer Pseudo Range messages. These are [rx], [rc],
[r1], [r2], [r3], [r5], [rl].
.RE
.sp
IRNSS
.RS 4
Disable use of the IRNSS constellation.
.RE
.sp
NMEA
.RS 4
Disable basic NMEA 4.1e messages at 4Hz. The messages are GBS, GGA,
GSA, GST, GSV, RMC, VTG, and ZDA.
.RE
.sp
QZSS
.RS 4
Disable use of the QZSS constellation.
.RE
.sp
SBAS
.RS 4
Disable use of the SBAS constellation.
.RE
.sp
SNR
.RS 4
Disable all SNR messages, except [EC]. The messages disabled are:
[E1], [E2], [E3], [E5], [El].
.RE
.RE
.sp
\fB\-e OPTION\fP
.RS 4
Enable an option in the GPS. Accepts one parameter, OPTION, the option
to enable. \fBzerk\fP will exit after the GPS acknowledges the command,
unless the \fB\-W\fP is given. \fB\-e\fP accepts the same OPTIONs as \fB\-d\fP, except the
action is to enable the option.
.RE
.sp
\fB\-f FILE\fP
.RS 4
Connect to a file or device. Accepts one parameter, FILE, the file or
device to open. Files are opened read\-only. Character devices are
opened read/write, unless the \-r parameter is given. Requires the
pyserial module.
.RE
.sp
\fB\-O OAF\fP
.RS 4
Load an Option Authorization File (OAF) into the GPS. Accepts one
parameter, OAF, command file to read. The OAF is just a special case
of a \*(Aq.jpo\*(Aq (GREIS command file). \-O will send any valid .jpo file to
the GPS.
.RE
.sp
\fB\-p PRESET\fP
.RS 4
Send a preset command the GPS. Accepts one parameter, PRESET, the name
of the command to send. \fBzerk\fP will exit after the GPS acknowledges the
command, unless the \fB\-W\fP is given.
.sp
COLDBOOT
.RS 4
Coldboot the GPS.
.RE
.sp
CONS
.RS 4
Poll the enabled constellations.
.RE
.sp
DM
.RS 4
Disable all periodic GREIS messages.
.RE
.sp
ID
.RS 4
Poll the receiver ID.
.RE
.sp
IPR
.RS 4
Poll all Integer Pseudo Range messages. These are [rx], [rc], [r1],
[r2], [r3], [r5], [rl].
.RE
.sp
OAF
.RS 4
Poll all OAF options.
.RE
.sp
RESET
.RS 4
Reset (reboot) the GPS.
.RE
.sp
SERIAL
.RS 4
Poll receiver serial number.
.RE
.sp
SNR
.RS 4
Poll all Signal to Noise Ratio (SNR) messages. [EC], [E1], [E2],
[E3], [E5], [El].
.RE
.sp
VENDOR
.RS 4
Poll GPS vendor.
.RE
.sp
VER
.RS 4
Poll GPS version.
.RE
.RE
.sp
\fB\-r\fP
.RS 4
Read only. Do not send anything to the GPS.
.RE
.sp
\fB\-R RAW\fP
.RS 4
Save all raw data from the GPS into the file RAW.
.RE
.sp
\fB\-S SPEED\fP
.RS 4
Configure the GPS serial speed to SPEED bps.
.RE
.sp
\fB\-s SPEED\fP
.RS 4
Set local serial port speed to SPEED bps. Default 115,200 bps.
.RE
.sp
\fB\-V\fP
.RS 4
Print \fBzerk\fP version and exit.
.RE
.sp
\fB\-v VERBOSITY\fP
.RS 4
Set verbosity level to VERBOSITY. Verbosity can be from 0 (very
quiet), to 4 (very noisy). Default 2.
.RE
.sp
\fB\-W\fP
.RS 4
Force waiting the entire wait time. No early exit for completion of
\fB\-d\fP, \fB\-e\fP or \fB\-p\fP command.
.RE
.sp
\fB\-w WAIT\fP
.RS 4
Wait for WAIT seconds before exiting. Will exit early on command
completion of \fB\-d\fP, \fB\-e\fP or \fB\-p\fP command, unless \fB\-W\fP is given. Default 2.0
second.
.RE
.SH "ARGUMENTS"
.sp
By default, clients collect data from the local \fBgpsd\fP daemon running
on localhost, using the default GPSD port 2947. The optional argument
to any client may override this behavior: \fB[server[:port[:device]]]\fP
.sp
For further explanation, and examples, see the \fBARGUMENTS\fP section in
the \fBgps\fP(1) man page
.SH "ENVIRONMENT"
.sp
Options can be placed in the ZERKOPTS environment variable. ZERKOPTS is
processed before the CLI options.
.SH "EXAMPLES"
.sp
Print current Javad serial port of GPS connected to local running
\fBgpsd\fP:
.sp
.if n .RS 4
.nf
.fam C
 zerk \-c "print,/cur/term"
.fam
.fi
.if n .RE
.sp
Decode raw log file:
.sp
.if n .RS 4
.nf
.fam C
zerk \-r \-f greis\-binary.log \-v 2
.fam
.fi
.if n .RE
.sp
Change GPS port speed of device on /dev/ttyAMA0 to 230,400 bps:
.sp
.if n .RS 4
.nf
.fam C
zerk \-S 230400 \-f /dev/ttyAMA0
.fam
.fi
.if n .RE
.sp
Watch entire GPS reset cycle:
.sp
.if n .RS 4
.nf
.fam C
zerk \-p RESET \-v 2 \-w 20 \-W
.fam
.fi
.if n .RE
.sp
Poll SVs Status:
.sp
.if n .RS 4
.nf
.fam C
zerk \-W \-w 2 \-v 2 \-c "out,,jps/{CS,ES,GS,Is,WS,QS}"
.fam
.fi
.if n .RE
.sp
Dump \fBgpsd\fP data from remote server:
.sp
.if n .RS 4
.nf
.fam C
zerk \-v 2 \-w 5 server
.fam
.fi
.if n .RE
.SH "RETURN VALUES"
.sp
\fB0\fP
.RS 4
on success.
.RE
.sp
\fB1\fP
.RS 4
on failure
.RE
.SH "SEE ALSO"
.sp
\fBzerk\fP is written to conform to the official Javad documentation for the
GREIS protocol.
.URL "https://www.javad.com/downloads/javadgnss/manuals/GREIS/GREIS_Reference_Guide.pdf" "GREIS Guide" "."
.sp
\fBgpsd\fP(8)
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://gpsd.io/" "" ""
.SH "COPYING"
.sp
This file is Copyright 2013 by the GPSD project
.br
SPDX\-License\-Identifier: BSD\-2\-clause
.SH "AUTHOR"
.sp
Gary E. Miller